services:
  app:
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - .env:/app/.env:ro

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - blueprint
