entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: alexandredissi@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false

log:
  level: INFO

api:
  dashboard: true
