package powens

type Subscription struct {
	Name     string
	Category string
}

var SubscriptionNames = []Subscription{
	// Streaming Vidéo

	{"Intermarche", "E-commerce & Livraisons"},
	{"Monoprix", "E-commerce & Livraisons"},
	{"Netflix", "Streaming Vidéo"},
	{"Disney+", "Streaming Vidéo"},
	{"Amazon Prime Video", "Streaming Vidéo"},
	{"Apple TV+", "Streaming Vidéo"},
	{"HBO Max", "Streaming Vidéo"},
	{"Hulu", "Streaming Vidéo"},
	{"Paramount+", "Streaming Vidéo"},
	{"Canal+", "Streaming Vidéo"},
	{"Crunchyroll", "Streaming Vidéo"},
	{"Funimation", "Streaming Vidéo"},
	{"WOW Presents Plus", "Streaming Vidéo"},
	{"Mubi", "Streaming Vidéo"},
	{"Peacock", "Streaming Vidéo"},
	{"Rakuten TV", "Streaming Vidéo"},
	{"Molotov", "Streaming Vidéo"},
	{"Starzplay", "Streaming Vidéo"},
	{"Shudder", "Streaming Vidéo"},
	{"Filmotv", "Streaming Vidéo"},
	{"Ovid.tv", "Streaming Vidéo"},
	{"Apple One", "Streaming Vidéo"},

	// Streaming Musique
	{"Spotify", "Streaming Musique"},
	{"Apple Music", "Streaming Musique"},
	{"Deezer", "Streaming Musique"},
	{"YouTube Music", "Streaming Musique"},
	{"Tidal", "Streaming Musique"},
	{"Amazon Music", "Streaming Musique"},
	{"Qobuz", "Streaming Musique"},
	{"SoundCloud Go+", "Streaming Musique"},
	{"Napster", "Streaming Musique"},
	{"Boomplay", "Streaming Musique"},
	{"Anghami", "Streaming Musique"},

	// Livres Audio & Presse
	{"Audible", "Livres Audio"},
	{"Scribd", "Livres Audio"},
	{"Kindle Unlimited", "Livres Audio"},
	{"YouScribe", "Livres Audio"},
	{"PressReader", "Actualités & Presse"},
	{"Spotify Audiobooks", "Livres Audio"},
	{"Le Monde", "Actualités & Presse"},
	{"Le Figaro", "Actualités & Presse"},
	{"Mediapart", "Actualités & Presse"},
	{"The New York Times", "Actualités & Presse"},
	{"Washington Post", "Actualités & Presse"},
	{"Les Échos", "Actualités & Presse"},

	// Stockage Cloud
	{"Google Drive", "Stockage Cloud"},
	{"Dropbox", "Stockage Cloud"},
	{"iCloud", "Stockage Cloud"},
	{"OneDrive", "Stockage Cloud"},
	{"pCloud", "Stockage Cloud"},
	{"Mega", "Stockage Cloud"},
	{"Amazon S3", "Stockage Cloud"},
	{"Backblaze", "Stockage Cloud"},
	{"Sync.com", "Stockage Cloud"},
	{"Box", "Stockage Cloud"},
	{"iDrive", "Stockage Cloud"},

	// Jeux Vidéo
	{"Xbox Game Pass", "Jeux Vidéo"},
	{"PlayStation Plus", "Jeux Vidéo"},
	{"Nintendo Switch Online", "Jeux Vidéo"},
	{"EA Play", "Jeux Vidéo"},
	{"Ubisoft+", "Jeux Vidéo"},
	{"GeForce Now", "Jeux Vidéo"},
	{"Apple Arcade", "Jeux Vidéo"},
	{"Shadow", "Jeux Vidéo"},
	{"Blacknut", "Jeux Vidéo"},
	{"Roblox Premium", "Jeux Vidéo"},
	{"Minecraft Realms", "Jeux Vidéo"},
	{"Luna (Amazon Gaming)", "Jeux Vidéo"},
	{"Battle.net Pass", "Jeux Vidéo"},
	{"Final Fantasy XIV Subscription", "Jeux Vidéo"},
	{"RuneScape Membership", "Jeux Vidéo"},
	{"Dofus Premium", "Jeux Vidéo"},

	// Productivité
	{"Microsoft 365", "Productivité"},
	{"Google Workspace", "Productivité"},
	{"Notion", "Productivité"},
	{"Evernote", "Productivité"},
	{"Trello", "Productivité"},
	{"Slack", "Productivité"},
	{"Zoom", "Productivité"},
	{"Adobe Creative Cloud", "Productivité"},
	{"Grammarly", "Productivité"},
	{"Canva", "Productivité"},
	{"Monday.com", "Productivité"},
	{"Asana", "Productivité"},
	{"ClickUp", "Productivité"},
	{"Todoist", "Productivité"},
	{"Obsidian Sync", "Productivité"},
	{"Basecamp", "Productivité"},
	{"Roam Research", "Productivité"},
	{"Bear Pro", "Productivité"},
	{"Superhuman", "Productivité"},
	{"Dropbox Paper", "Productivité"},

	// Fitness & Bien-être
	{"MyFitnessPal", "Fitness & Bien-être"},
	{"Strava", "Fitness & Bien-être"},
	{"Fitbit Premium", "Fitness & Bien-être"},
	{"Apple Fitness+", "Fitness & Bien-être"},
	{"Peloton", "Fitness & Bien-être"},
	{"Headspace", "Fitness & Bien-être"},
	{"Calm", "Fitness & Bien-être"},
	{"Nike Training Club", "Fitness & Bien-être"},
	{"LesMills+", "Fitness & Bien-être"},
	{"WW (Weight Watchers)", "Fitness & Bien-être"},
	{"8fit", "Fitness & Bien-être"},
	{"Sweat", "Fitness & Bien-être"},
	{"Alo Moves", "Fitness & Bien-être"},
	{"Glo Yoga", "Fitness & Bien-être"},
	{"Nike Run Club Premium", "Fitness & Bien-être"},

	// Éducation
	{"Udemy", "Éducation"},
	{"Coursera", "Éducation"},
	{"MasterClass", "Éducation"},
	{"Skillshare", "Éducation"},
	{"LinkedIn Learning", "Éducation"},
	{"Duolingo Plus", "Éducation"},
	{"Brilliant", "Éducation"},
	{"Khan Academy", "Éducation"},
	{"Codecademy", "Éducation"},
	{"Rosetta Stone", "Éducation"},
	{"DataCamp", "Éducation"},
	{"edX Premium", "Éducation"},
	{"Memrise Pro", "Éducation"},
	{"SoloLearn Pro", "Éducation"},
	{"Pluralsight", "Éducation"},

	// Cybersécurité
	{"NordVPN", "CyberSécurité"},
	{"ExpressVPN", "CyberSécurité"},
	{"Surfshark", "CyberSécurité"},
	{"ProtonVPN", "CyberSécurité"},
	{"CyberGhost", "CyberSécurité"},
	{"1Password", "CyberSécurité"},
	{"LastPass", "CyberSécurité"},
	{"Dashlane", "CyberSécurité"},
	{"ProtonMail", "CyberSécurité"},
	{"Malwarebytes Premium", "CyberSécurité"},
	{"TunnelBear VPN", "CyberSécurité"},
	{"Proton Pass", "CyberSécurité"},
	{"Bitwarden Premium", "CyberSécurité"},

	// E-commerce & Livraisons
	{"Amazon Prime", "E-commerce & Livraisons"},
	{"Walmart+", "E-commerce & Livraisons"},
	{"Shopify", "E-commerce & Livraisons"},
	{"Deliveroo Plus", "E-commerce & Livraisons"},
	{"Uber One", "E-commerce & Livraisons"},
	{"Instacart+", "E-commerce & Livraisons"},
	{"Carrefour+", "E-commerce & Livraisons"},
	{"Auchan Pass", "E-commerce & Livraisons"},
	{"Casino Max Extra", "E-commerce & Livraisons"},
	{"U Express Pass", "E-commerce & Livraisons"},
	{"Franprix Plus", "E-commerce & Livraisons"},

	// Mode et Beauté
	{"Sephora Flash", "Mode & Beauté"},
	{"Zalando Plus", "Mode & Beauté"},
	{"H&M Membership", "Mode & Beauté"},
	{"ASOS Premier", "Mode & Beauté"},
	{"Nike Membership", "Mode & Beauté"},
	{"Beauty Pie", "Mode & Beauté"},

	// Automobile & Transport
	{"Tesla Premium Connectivity", "Automobile & Transport"},
	{"Free2Move", "Automobile & Transport"},
	{"Lime Pass", "Automobile & Transport"},
	{"Bird+", "Automobile & Transport"},
	{"BlaBlaCar+", "Automobile & Transport"},
	{"Uber Ride Pass", "Automobile & Transport"},
	{"Lyft Pink", "Automobile & Transport"},
	{"CityScoot Pass", "Automobile & Transport"},
	{"DriveNow", "Automobile & Transport"},
	{"TIER Monthly Pass", "Automobile & Transport"},
	{"Vélib", "Automobile & Transport"},

	// App de Rencontres
	{"Tinder Plus", "App de Rencontres"},
	{"Bumble Boost", "App de Rencontres"},
	{"Happn Premium", "App de Rencontres"},
	{"Once VIP", "App de Rencontres"},
	{"Meetic Premium", "App de Rencontres"},
	{"AdopteUnMec", "App de Rencontres"},
	{"Grindr Xtra", "App de Rencontres"},
	{"OkCupid Premium", "App de Rencontres"},
	{"EliteRencontre", "App de Rencontres"},
	{"eDarling", "App de Rencontres"},
	{"Attractive World", "App de Rencontres"},
	{"DisonsDemain", "App de Rencontres"},
	{"OurTime", "App de Rencontres"},
}
