package powens

import "regexp"

type SubscriptionList struct {
	Name     string
	Category string
	Regex    *regexp.Regexp
}

var SubscriptionNames = []SubscriptionList{
	{"Netflix", "Streaming Vidéo", regexp.MustCompile(`(?i)(Netflix|CB\*.*Netflix|PAYPAL.*Netflix)`)},
	{"Disney+", "Streaming Vidéo", regexp.MustCompile(`(?i)(Disney\+|CB\*.*Disney\+|PAYPAL.*Disney\+)`)},
	{"Amazon Prime Video", "Streaming Vidéo", regexp.MustCompile(`(?i)(Amazon.*Prime.*Video|AMZN.*VIDEO|CB\*.*AMZN.*VIDEO|PAYPAL.*AMZN.*VIDEO)`)},
	{"Apple TV+", "Streaming Vidéo", regexp.MustCompile(`(?i)(Apple.*TV\+|APPLE\.COM/BILL|CB\*.*APPLE|PAYPAL.*APPLE)`)},
	{"HBO Max", "Streaming Vidéo", regexp.MustCompile(`(?i)(HBO.*Max|CB\*.*HBO|PAYPAL.*HBO)`)},
	{"Hulu", "Streaming Vidéo", regexp.MustCompile(`(?i)(Hulu|CB\*.*Hulu|PAYPAL.*Hulu)`)},
	{"Paramount+", "Streaming Vidéo", regexp.MustCompile(`(?i)(Paramount\+|CB\*.*Paramount|PAYPAL.*Paramount)`)},
	{"Canal+", "Streaming Vidéo", regexp.MustCompile(`(?i)(Canal\+|CB\*.*Canal|PAYPAL.*Canal)`)},
	{"Crunchyroll", "Streaming Vidéo", regexp.MustCompile(`(?i)(Crunchyroll|CB\*.*Crunchyroll|PAYPAL.*Crunchyroll)`)},
	{"Funimation", "Streaming Vidéo", regexp.MustCompile(`(?i)(Funimation|CB\*.*Funimation|PAYPAL.*Funimation)`)},
	{"WOW Presents Plus", "Streaming Vidéo", regexp.MustCompile(`(?i)(WOW.*Presents.*Plus|CB\*.*WOW|PAYPAL.*WOW)`)},
	{"Mubi", "Streaming Vidéo", regexp.MustCompile(`(?i)(Mubi|CB\*.*Mubi|PAYPAL.*Mubi)`)},
	{"Peacock", "Streaming Vidéo", regexp.MustCompile(`(?i)(Peacock|CB\*.*Peacock|PAYPAL.*Peacock)`)},
	{"Rakuten TV", "Streaming Vidéo", regexp.MustCompile(`(?i)(Rakuten.*TV|CB\*.*Rakuten|PAYPAL.*Rakuten)`)},
	{"Molotov", "Streaming Vidéo", regexp.MustCompile(`(?i)(Molotov|CB\*.*Molotov|PAYPAL.*Molotov)`)},
	{"Starzplay", "Streaming Vidéo", regexp.MustCompile(`(?i)(Starzplay|CB\*.*Starzplay|PAYPAL.*Starzplay)`)},
	{"Shudder", "Streaming Vidéo", regexp.MustCompile(`(?i)(Shudder|CB\*.*Shudder|PAYPAL.*Shudder)`)},
	{"Filmotv", "Streaming Vidéo", regexp.MustCompile(`(?i)(Filmotv|CB\*.*Filmotv|PAYPAL.*Filmotv)`)},
	{"Ovid.tv", "Streaming Vidéo", regexp.MustCompile(`(?i)(Ovid\.tv|CB\*.*Ovid|PAYPAL.*Ovid)`)},
	{"Apple One", "Streaming Vidéo", regexp.MustCompile(`(?i)(Apple.*One|APPLE\.COM/BILL|CB\*.*APPLE|PAYPAL.*APPLE)`)},

	// Streaming Musique
	{"Spotify", "Streaming Musique", regexp.MustCompile(`(?i)(Spotify|CB\*.*Spotify|PAYPAL.*Spotify)`)},
	{"Apple Music", "Streaming Musique", regexp.MustCompile(`(?i)(Apple.*Music|APPLE\.COM/BILL|CB\*.*APPLE|PAYPAL.*APPLE)`)},
	{"Deezer", "Streaming Musique", regexp.MustCompile(`(?i)(Deezer|CB\*.*Deezer|PAYPAL.*Deezer)`)},
	{"YouTube Music", "Streaming Musique", regexp.MustCompile(`(?i)(YouTube.*Music|CB\*.*YouTube|PAYPAL.*YouTube)`)},
	{"Tidal", "Streaming Musique", regexp.MustCompile(`(?i)(Tidal|CB\*.*Tidal|PAYPAL.*Tidal)`)},
	{"Amazon Music", "Streaming Musique", regexp.MustCompile(`(?i)(Amazon.*Music|AMZN.*MUSIC|CB\*.*AMZN.*MUSIC|PAYPAL.*AMZN.*MUSIC)`)},
	{"Qobuz", "Streaming Musique", regexp.MustCompile(`(?i)(Qobuz|CB\*.*Qobuz|PAYPAL.*Qobuz)`)},
	{"SoundCloud Go+", "Streaming Musique", regexp.MustCompile(`(?i)(SoundCloud.*Go\+|CB\*.*SoundCloud|PAYPAL.*SoundCloud)`)},
	{"Napster", "Streaming Musique", regexp.MustCompile(`(?i)(Napster|CB\*.*Napster|PAYPAL.*Napster)`)},
	{"Boomplay", "Streaming Musique", regexp.MustCompile(`(?i)(Boomplay|CB\*.*Boomplay|PAYPAL.*Boomplay)`)},
	{"Anghami", "Streaming Musique", regexp.MustCompile(`(?i)(Anghami|CB\*.*Anghami|PAYPAL.*Anghami)`)},

	// Livres Audio & Presse
	{"Audible", "Livres Audio", regexp.MustCompile(`(?i)(Audible|CB\*.*Audible|PAYPAL.*Audible)`)},
	{"Scribd", "Livres Audio", regexp.MustCompile(`(?i)(Scribd|CB\*.*Scribd|PAYPAL.*Scribd)`)},
	{"Kindle Unlimited", "Livres Audio", regexp.MustCompile(`(?i)(Kindle.*Unlimited|AMZN.*KINDLE|CB\*.*AMZN.*KINDLE|PAYPAL.*AMZN.*KINDLE)`)},
	{"YouScribe", "Livres Audio", regexp.MustCompile(`(?i)(YouScribe|CB\*.*YouScribe|PAYPAL.*YouScribe)`)},
	{"PressReader", "Actualités & Presse", regexp.MustCompile(`(?i)(PressReader|CB\*.*PressReader|PAYPAL.*PressReader)`)},
	{"Spotify Audiobooks", "Livres Audio", regexp.MustCompile(`(?i)(Spotify.*Audiobooks|CB\*.*Spotify|PAYPAL.*Spotify)`)},
	{"Le Monde", "Actualités & Presse", regexp.MustCompile(`(?i)(Le.*Monde|CB\*.*LeMonde|PAYPAL.*LeMonde)`)},
	{"Le Figaro", "Actualités & Presse", regexp.MustCompile(`(?i)(Le.*Figaro|CB\*.*LeFigaro|PAYPAL.*LeFigaro)`)},
	{"Mediapart", "Actualités & Presse", regexp.MustCompile(`(?i)(Mediapart|CB\*.*Mediapart|PAYPAL.*Mediapart)`)},
	{"The New York Times", "Actualités & Presse", regexp.MustCompile(`(?i)(The.*New.*York.*Times|CB\*.*NYTimes|PAYPAL.*NYTimes)`)},
	{"Washington Post", "Actualités & Presse", regexp.MustCompile(`(?i)(Washington.*Post|CB\*.*WaPo|PAYPAL.*WaPo)`)},
	{"Les Échos", "Actualités & Presse", regexp.MustCompile(`(?i)(Les.*Échos|CB\*.*LesEchos|PAYPAL.*LesEchos)`)},

	// Stockage Cloud
	{"Google Drive", "Stockage Cloud", regexp.MustCompile(`(?i)(Google.*Drive|GOOGLE.*DRIVE|CB\*.*GOOGLE|PAYPAL.*GOOGLE)`)},
	{"Dropbox", "Stockage Cloud", regexp.MustCompile(`(?i)(Dropbox|CB\*.*Dropbox|PAYPAL.*Dropbox)`)},
	{"iCloud", "Stockage Cloud", regexp.MustCompile(`(?i)(iCloud|APPLE\.COM/BILL|CB\*.*APPLE|PAYPAL.*APPLE)`)},
	{"OneDrive", "Stockage Cloud", regexp.MustCompile(`(?i)(OneDrive|CB\*.*OneDrive|PAYPAL.*OneDrive)`)},
	{"pCloud", "Stockage Cloud", regexp.MustCompile(`(?i)(pCloud|CB\*.*pCloud|PAYPAL.*pCloud)`)},
	{"Mega", "Stockage Cloud", regexp.MustCompile(`(?i)(Mega|CB\*.*Mega|PAYPAL.*Mega)`)},
	{"Amazon S3", "Stockage Cloud", regexp.MustCompile(`(?i)(Amazon.*S3|AMZN.*S3|CB\*.*AMZN.*S3|PAYPAL.*AMZN.*S3)`)},
	{"HubiC", "Stockage Cloud", regexp.MustCompile(`(?i)(HubiC|CB\*.*HubiC|PAYPAL.*HubiC)`)},
	{"Scaleway", "Stockage Cloud", regexp.MustCompile(`(?i)(Scaleway|CB\*.*Scaleway|PAYPAL.*Scaleway)`)},
	{"OVHcloud", "Stockage Cloud", regexp.MustCompile(`(?i)(OVHcloud|CB\*.*OVHcloud|PAYPAL.*OVHcloud)`)},
	{"Backblaze", "Stockage Cloud", regexp.MustCompile(`(?i)(Backblaze|CB\*.*Backblaze|PAYPAL.*Backblaze)`)},
	{"Wasabi", "Stockage Cloud", regexp.MustCompile(`(?i)(Wasabi|CB\*.*Wasabi|PAYPAL.*Wasabi)`)},
	{"pCloud Crypto", "Stockage Cloud", regexp.MustCompile(`(?i)(pCloud.*Crypto|CB\*.*pCloud|PAYPAL.*pCloud)`)},
	{"Sync", "Stockage Cloud", regexp.MustCompile(`(?i)(Sync|CB\*.*Sync|PAYPAL.*Sync)`)},

	// Jeux Vidéo
	{"Xbox Game Pass", "Jeux Vidéo", regexp.MustCompile(`(?i)(Xbox.*Game.*Pass|CB\*.*Xbox|PAYPAL.*Xbox)`)},
	{"PlayStation Plus", "Jeux Vidéo", regexp.MustCompile(`(?i)(PlayStation.*Plus|CB\*.*PlayStation|PAYPAL.*PlayStation)`)},
	{"Nintendo Switch Online", "Jeux Vidéo", regexp.MustCompile(`(?i)(Nintendo.*Switch.*Online|CB\*.*Nintendo|PAYPAL.*Nintendo)`)},
	{"EA Play", "Jeux Vidéo", regexp.MustCompile(`(?i)(EA.*Play|CB\*.*EA|PAYPAL.*EA)`)},
	{"Ubisoft+", "Jeux Vidéo", regexp.MustCompile(`(?i)(Ubisoft\+|CB\*.*Ubisoft|PAYPAL.*Ubisoft)`)},
	{"GeForce Now", "Jeux Vidéo", regexp.MustCompile(`(?i)(GeForce.*Now|CB\*.*GeForce|PAYPAL.*GeForce)`)},
	{"Apple Arcade", "Jeux Vidéo", regexp.MustCompile(`(?i)(Apple.*Arcade|APPLE\.COM/BILL|CB\*.*APPLE|PAYPAL.*APPLE)`)},
	{"Shadow", "Jeux Vidéo", regexp.MustCompile(`(?i)(Shadow|CB\*.*Shadow|PAYPAL.*Shadow)`)},
	{"Blacknut", "Jeux Vidéo", regexp.MustCompile(`(?i)(Blacknut|CB\*.*Blacknut|PAYPAL.*Blacknut)`)},
	{"Roblox Premium", "Jeux Vidéo", regexp.MustCompile(`(?i)(Roblox.*Premium|CB\*.*Roblox|PAYPAL.*Roblox)`)},
	{"Minecraft Realms", "Jeux Vidéo", regexp.MustCompile(`(?i)(Minecraft.*Realms|CB\*.*Minecraft|PAYPAL.*Minecraft)`)},
	{"Luna (Amazon Gaming)", "Jeux Vidéo", regexp.MustCompile(`(?i)(Luna.*\(Amazon.*Gaming\)|AMZN.*LUNA|CB\*.*AMZN.*LUNA|PAYPAL.*AMZN.*LUNA)`)},
	{"Battle.net Pass", "Jeux Vidéo", regexp.MustCompile(`(?i)(Battle\.net.*Pass|CB\*.*Battle|PAYPAL.*Battle)`)},
	{"Final Fantasy XIV Subscription", "Jeux Vidéo", regexp.MustCompile(`(?i)(Final.*Fantasy.*XIV.*Subscription|CB\*.*FFXIV|PAYPAL.*FFXIV)`)},
	{"RuneScape Membership", "Jeux Vidéo", regexp.MustCompile(`(?i)(RuneScape.*Membership|CB\*.*RuneScape|PAYPAL.*RuneScape)`)},
	{"Dofus Premium", "Jeux Vidéo", regexp.MustCompile(`(?i)(Dofus.*Premium|CB\*.*Dofus|PAYPAL.*Dofus)`)},

	// Productivité
	{"Microsoft 365", "Productivité", regexp.MustCompile(`(?i)(Microsoft.*365|CB\*.*Microsoft|PAYPAL.*Microsoft)`)},
	{"Google Workspace", "Productivité", regexp.MustCompile(`(?i)(Google.*Workspace|GOOGLE.*WORKSPACE|CB\*.*GOOGLE|PAYPAL.*GOOGLE)`)},
	{"Notion", "Productivité", regexp.MustCompile(`(?i)(Notion|CB\*.*Notion|PAYPAL.*Notion)`)},
	{"Evernote", "Productivité", regexp.MustCompile(`(?i)(Evernote|CB\*.*Evernote|PAYPAL.*Evernote)`)},
	{"Trello", "Productivité", regexp.MustCompile(`(?i)(Trello|CB\*.*Trello|PAYPAL.*Trello)`)},
	{"Slack", "Productivité", regexp.MustCompile(`(?i)(Slack|CB\*.*Slack|PAYPAL.*Slack)`)},
	{"Zoom", "Productivité", regexp.MustCompile(`(?i)(Zoom|CB\*.*Zoom|PAYPAL.*Zoom)`)},
	{"Adobe Creative Cloud", "Productivité", regexp.MustCompile(`(?i)(Adobe.*Creative.*Cloud|CB\*.*Adobe|PAYPAL.*Adobe)`)},
	{"Grammarly", "Productivité", regexp.MustCompile(`(?i)(Grammarly|CB\*.*Grammarly|PAYPAL.*Grammarly)`)},
	{"Canva", "Productivité", regexp.MustCompile(`(?i)(Canva|CB\*.*Canva|PAYPAL.*Canva)`)},
	{"Monday.com", "Productivité", regexp.MustCompile(`(?i)(Monday\.com|CB\*.*Monday|PAYPAL.*Monday)`)},
	{"Asana", "Productivité", regexp.MustCompile(`(?i)(Asana|CB\*.*Asana|PAYPAL.*Asana)`)},
	{"ClickUp", "Productivité", regexp.MustCompile(`(?i)(ClickUp|CB\*.*ClickUp|PAYPAL.*ClickUp)`)},
	{"Todoist", "Productivité", regexp.MustCompile(`(?i)(Todoist|CB\*.*Todoist|PAYPAL.*Todoist)`)},
	{"Obsidian Sync", "Productivité", regexp.MustCompile(`(?i)(Obsidian.*Sync|CB\*.*Obsidian|PAYPAL.*Obsidian)`)},
	{"Basecamp", "Productivité", regexp.MustCompile(`(?i)(Basecamp|CB\*.*Basecamp|PAYPAL.*Basecamp)`)},
	{"Roam Research", "Productivité", regexp.MustCompile(`(?i)(Roam.*Research|CB\*.*Roam|PAYPAL.*Roam)`)},
	{"Bear Pro", "Productivité", regexp.MustCompile(`(?i)(Bear.*Pro|CB\*.*Bear|PAYPAL.*Bear)`)},
	{"Superhuman", "Productivité", regexp.MustCompile(`(?i)(Superhuman|CB\*.*Superhuman|PAYPAL.*Superhuman)`)},
	{"Dropbox Paper", "Productivité", regexp.MustCompile(`(?i)(Dropbox.*Paper|CB\*.*Dropbox|PAYPAL.*Dropbox)`)},

	// Fitness & Bien-être
	{"MyFitnessPal", "Fitness & Bien-être", regexp.MustCompile(`(?i)(MyFitnessPal|CB\*.*MyFitnessPal|PAYPAL.*MyFitnessPal)`)},
	{"Strava", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Strava|CB\*.*Strava|PAYPAL.*Strava)`)},
	{"Fitbit Premium", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Fitbit.*Premium|CB\*.*Fitbit|PAYPAL.*Fitbit)`)},
	{"Apple Fitness+", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Apple.*Fitness\+|APPLE\.COM/BILL|CB\*.*APPLE|PAYPAL.*APPLE)`)},
	{"Peloton", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Peloton|CB\*.*Peloton|PAYPAL.*Peloton)`)},
	{"Headspace", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Headspace|CB\*.*Headspace|PAYPAL.*Headspace)`)},
	{"Calm", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Calm|CB\*.*Calm|PAYPAL.*Calm)`)},
	{"Nike Training Club", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Nike.*Training.*Club|CB\*.*Nike|PAYPAL.*Nike)`)},
	{"LesMills+", "Fitness & Bien-être", regexp.MustCompile(`(?i)(LesMills\+|CB\*.*LesMills|PAYPAL.*LesMills)`)},
	{"WW (Weight Watchers)", "Fitness & Bien-être", regexp.MustCompile(`(?i)(WW.*\(Weight.*Watchers\)|CB\*.*WW|PAYPAL.*WW)`)},
	{"8fit", "Fitness & Bien-être", regexp.MustCompile(`(?i)(8fit|CB\*.*8fit|PAYPAL.*8fit)`)},
	{"Sweat", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Sweat|CB\*.*Sweat|PAYPAL.*Sweat)`)},
	{"Alo Moves", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Alo.*Moves|CB\*.*Alo|PAYPAL.*Alo)`)},
	{"Glo Yoga", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Glo.*Yoga|CB\*.*Glo|PAYPAL.*Glo)`)},
	{"Nike Run Club Premium", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Nike.*Run.*Club.*Premium|CB\*.*Nike|PAYPAL.*Nike)`)},
	{"Basic-Fit", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Basic-Fit|CB\*.*BasicFit|PAYPAL.*BasicFit)`)},
	{"Keep Cool", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Keep.*Cool|CB\*.*KeepCool|PAYPAL.*KeepCool)`)},
	{"Fitlane", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Fitlane|CB\*.*Fitlane|PAYPAL.*Fitlane)`)},
	{"L'Appart Fitness", "Fitness & Bien-être", regexp.MustCompile(`(?i)(L'Appart.*Fitness|CB\*.*LAppart|PAYPAL.*LAppart)`)},
	{"Moving", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Moving|CB\*.*Moving|PAYPAL.*Moving)`)},
	{"Magic Form", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Magic.*Form|CB\*.*MagicForm|PAYPAL.*MagicForm)`)},
	{"Orange Bleue", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Orange.*Bleue|CB\*.*OrangeBleue|PAYPAL.*OrangeBleue)`)},
	{"Fitness Park", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Fitness.*Park|CB\*.*FitnessPark|PAYPAL.*FitnessPark)`)},
	{"Keep Cool", "Fitness & Bien-être", regexp.MustCompile(`(?i)(Keep.*Cool|CB\*.*KeepCool|PAYPAL.*KeepCool)`)},
	// Éducation
	{"Udemy", "Éducation", regexp.MustCompile(`(?i)(Udemy|CB\*.*Udemy|PAYPAL.*Udemy)`)},
	{"Coursera", "Éducation", regexp.MustCompile(`(?i)(Coursera|CB\*.*Coursera|PAYPAL.*Coursera)`)},
	{"MasterClass", "Éducation", regexp.MustCompile(`(?i)(MasterClass|CB\*.*MasterClass|PAYPAL.*MasterClass)`)},
	{"Skillshare", "Éducation", regexp.MustCompile(`(?i)(Skillshare|CB\*.*Skillshare|PAYPAL.*Skillshare)`)},
	{"LinkedIn Learning", "Éducation", regexp.MustCompile(`(?i)(LinkedIn.*Learning|CB\*.*LinkedIn|PAYPAL.*LinkedIn)`)},
	{"Duolingo Plus", "Éducation", regexp.MustCompile(`(?i)(Duolingo.*Plus|CB\*.*Duolingo|PAYPAL.*Duolingo)`)},
	{"Brilliant", "Éducation", regexp.MustCompile(`(?i)(Brilliant|CB\*.*Brilliant|PAYPAL.*Brilliant)`)},
	{"Khan Academy", "Éducation", regexp.MustCompile(`(?i)(Khan.*Academy|CB\*.*Khan|PAYPAL.*Khan)`)},
	{"Codecademy", "Éducation", regexp.MustCompile(`(?i)(Codecademy|CB\*.*Codecademy|PAYPAL.*Codecademy)`)},
	{"Rosetta Stone", "Éducation", regexp.MustCompile(`(?i)(Rosetta.*Stone|CB\*.*Rosetta|PAYPAL.*Rosetta)`)},
	{"DataCamp", "Éducation", regexp.MustCompile(`(?i)(DataCamp|CB\*.*DataCamp|PAYPAL.*DataCamp)`)},
	{"edX Premium", "Éducation", regexp.MustCompile(`(?i)(edX.*Premium|CB\*.*edX|PAYPAL.*edX)`)},
	{"Memrise Pro", "Éducation", regexp.MustCompile(`(?i)(Memrise.*Pro|CB\*.*Memrise|PAYPAL.*Memrise)`)},
	{"SoloLearn Pro", "Éducation", regexp.MustCompile(`(?i)(SoloLearn.*Pro|CB\*.*SoloLearn|PAYPAL.*SoloLearn)`)},
	{"Pluralsight", "Éducation", regexp.MustCompile(`(?i)(Pluralsight|CB\*.*Pluralsight|PAYPAL.*Pluralsight)`)},

	// Cybersécurité
	{"NordVPN", "CyberSécurité", regexp.MustCompile(`(?i)(NordVPN|CB\*.*NordVPN|PAYPAL.*NordVPN)`)},
	{"ExpressVPN", "CyberSécurité", regexp.MustCompile(`(?i)(ExpressVPN|CB\*.*ExpressVPN|PAYPAL.*ExpressVPN)`)},
	{"Surfshark", "CyberSécurité", regexp.MustCompile(`(?i)(Surfshark|CB\*.*Surfshark|PAYPAL.*Surfshark)`)},
	{"ProtonVPN", "CyberSécurité", regexp.MustCompile(`(?i)(ProtonVPN|CB\*.*ProtonVPN|PAYPAL.*ProtonVPN)`)},
	{"CyberGhost", "CyberSécurité", regexp.MustCompile(`(?i)(CyberGhost|CB\*.*CyberGhost|PAYPAL.*CyberGhost)`)},
	{"1Password", "CyberSécurité", regexp.MustCompile(`(?i)(1Password|CB\*.*1Password|PAYPAL.*1Password)`)},
	{"LastPass", "CyberSécurité", regexp.MustCompile(`(?i)(LastPass|CB\*.*LastPass|PAYPAL.*LastPass)`)},
	{"Dashlane", "CyberSécurité", regexp.MustCompile(`(?i)(Dashlane|CB\*.*Dashlane|PAYPAL.*Dashlane)`)},
	{"ProtonMail", "CyberSécurité", regexp.MustCompile(`(?i)(ProtonMail|CB\*.*ProtonMail|PAYPAL.*ProtonMail)`)},
	{"Malwarebytes Premium", "CyberSécurité", regexp.MustCompile(`(?i)(Malwarebytes.*Premium|CB\*.*Malwarebytes|PAYPAL.*Malwarebytes)`)},
	{"TunnelBear VPN", "CyberSécurité", regexp.MustCompile(`(?i)(TunnelBear.*VPN|CB\*.*TunnelBear|PAYPAL.*TunnelBear)`)},
	{"Proton Pass", "CyberSécurité", regexp.MustCompile(`(?i)(Proton.*Pass|CB\*.*Proton|PAYPAL.*Proton)`)},
	{"Bitwarden Premium", "CyberSécurité", regexp.MustCompile(`(?i)(Bitwarden.*Premium|CB\*.*Bitwarden|PAYPAL.*Bitwarden)`)},

	// E-commerce & Livraisons
	{"Amazon Prime", "E-commerce & Livraisons", regexp.MustCompile(`(?i)(Amazon.*Prime|AMZN.*PRIME|CB\*.*AMZN.*PRIME|PAYPAL.*AMZN.*PRIME)`)},
	{"Walmart+", "E-commerce & Livraisons", regexp.MustCompile(`(?i)(Walmart\+|CB\*.*Walmart|PAYPAL.*Walmart)`)},
	{"Shopify", "E-commerce & Livraisons", regexp.MustCompile(`(?i)(Shopify|CB\*.*Shopify|PAYPAL.*Shopify)`)},
	{"Deliveroo Plus", "E-commerce & Livraisons", regexp.MustCompile(`(?i)(Deliveroo.*Plus|CB\*.*Deliveroo|PAYPAL.*Deliveroo)`)},
	{"Uber One", "E-commerce & Livraisons", regexp.MustCompile(`(?i)(Uber.*One|CB\*.*Uber|PAYPAL.*Uber)`)},

	// Mode et Beauté
	{"Sephora Flash", "Mode & Beauté", regexp.MustCompile(`(?i)(Sephora.*Flash|CB\*.*Sephora|PAYPAL.*Sephora)`)},
	{"Zalando Plus", "Mode & Beauté", regexp.MustCompile(`(?i)(Zalando.*Plus|CB\*.*Zalando|PAYPAL.*Zalando)`)},
	{"H&M Membership", "Mode & Beauté", regexp.MustCompile(`(?i)(H&M.*Membership|CB\*.*HM|PAYPAL.*HM)`)},
	{"ASOS Premier", "Mode & Beauté", regexp.MustCompile(`(?i)(ASOS.*Premier|CB\*.*ASOS|PAYPAL.*ASOS)`)},
	{"Nike Membership", "Mode & Beauté", regexp.MustCompile(`(?i)(Nike.*Membership|CB\*.*Nike|PAYPAL.*Nike)`)},
	{"Beauty Pie", "Mode & Beauté", regexp.MustCompile(`(?i)(Beauty.*Pie|CB\*.*BeautyPie|PAYPAL.*BeautyPie)`)},

	{"HelloFresh", "Livraison de Repas", regexp.MustCompile(`(?i)(HelloFresh|CB\*.*HelloFresh|PAYPAL.*HelloFresh)`)},
	{"TooGoodToGo", "Anti-Gaspi", regexp.MustCompile(`(?i)(TooGoodToGo|CB\*.*TooGoodToGo|PAYPAL.*TooGoodToGo)`)},
	{"Cheerz", "Impression Photo", regexp.MustCompile(`(?i)(Cheerz|CB\*.*Cheerz|PAYPAL.*Cheerz)`)},
	{"Wescape", "Jeux d'évasion", regexp.MustCompile(`(?i)(Wescape|CB\*.*Wescape|PAYPAL.*Wescape)`)},
	{"Koober", "Résumés de livres", regexp.MustCompile(`(?i)(Koober|CB\*.*Koober|PAYPAL.*Koober)`)},
	{"Babbel", "Apprentissage de langues", regexp.MustCompile(`(?i)(Babbel|CB\*.*Babbel|PAYPAL.*Babbel)`)},
	{"Pret a pousser", "Jardinage d'intérieur", regexp.MustCompile(`(?i)(Pret a pousser|CB\*.*PretAPousser|PAYPAL.*PretAPousser)`)},
	{"Veepee", "Ventes privées", regexp.MustCompile(`(?i)(Veepee|CB\*.*Veepee|PAYPAL.*Veepee)`)},
	{"Showroomprivé", "Ventes privées", regexp.MustCompile(`(?i)(Showroomprivé|CB\*.*Showroomprive|PAYPAL.*Showroomprive)`)},
	{"Degustabox", "Box alimentaire", regexp.MustCompile(`(?i)(Degustabox|CB\*.*Degustabox|PAYPAL.*Degustabox)`)},
	{"Petit Bac", "Jeux", regexp.MustCompile(`(?i)(Petit Bac|CB\*.*PetitBac|PAYPAL.*PetitBac)`)},
	{"Jungo", "Jeux", regexp.MustCompile(`(?i)(Jungo|CB\*.*Jungo|PAYPAL.*Jungo)`)},
	{"Pass Culture", "Culture", regexp.MustCompile(`(?i)(Pass Culture|CB\*.*PassCulture|PAYPAL.*PassCulture)`)},
	{"Yuka", "Application alimentaire", regexp.MustCompile(`(?i)(Yuka|CB\*.*Yuka|PAYPAL.*Yuka)`)},
	{"ScanUp", "Application alimentaire", regexp.MustCompile(`(?i)(ScanUp|CB\*.*ScanUp|PAYPAL.*ScanUp)`)},
	{"Comme j'aime", "Régime alimentaire", regexp.MustCompile(`(?i)(Comme j'aime|CB\*.*CommeJaime|PAYPAL.*CommeJaime)`)},
	{"Weight watchers", "Régime alimentaire", regexp.MustCompile(`(?i)(Weight watchers|CB\*.*WeightWatchers|PAYPAL.*WeightWatchers)`)},
	{"Naturhouse", "Régime alimentaire", regexp.MustCompile(`(?i)(Naturhouse|CB\*.*Naturhouse|PAYPAL.*Naturhouse)`)},
	{"Dietplus", "Régime alimentaire", regexp.MustCompile(`(?i)(Dietplus|CB\*.*Dietplus|PAYPAL.*Dietplus)`)},
	{"Anahana", "Bien être", regexp.MustCompile(`(?i)(Anahana|CB\*.*Anahana|PAYPAL.*Anahana)`)},
	{"Petit Bambou", "Bien être", regexp.MustCompile(`(?i)(Petit Bambou|CB\*.*PetitBambou|PAYPAL.*PetitBambou)`)},
	{"Moodo", "Bien être", regexp.MustCompile(`(?i)(Moodo|CB\*.*Moodo|PAYPAL.*Moodo)`)},

	{"Apple", "Services Apple", regexp.MustCompile(`(?i)(Apple|iTunes|iCloud|Arcade|TV\+|Music|CB\*.*APPLE|PAYPAL.*APPLE|APPLE\.COM/BILL)`)},
	{"Google", "Services Google", regexp.MustCompile(`(?i)(Google|YouTube|Drive|Workspace|CB\*.*GOOGLE|PAYPAL.*GOOGLE|GOOGLE.*CLOUD|GOOGLE.*DRIVE|GOOGLE.*WORKSPACE)`)},
	{"Amazon", "Services Amazon", regexp.MustCompile(`(?i)(Amazon|AMZN|Prime|Video|Music|Kindle|Luna|CB\*.*AMZN|PAYPAL.*AMZN|AMZN.*PRIME|AMZN.*VIDEO|AMZN.*MUSIC)`)},
	{"Microsoft", "Services Microsoft", regexp.MustCompile(`(?i)(Microsoft|365|Xbox|CB\*.*MICROSOFT|PAYPAL.*MICROSOFT|MICROSOFT.*365)`)},
	{"Adobe", "Services Adobe", regexp.MustCompile(`(?i)(Adobe|Creative|Cloud|CB\*.*ADOBE|PAYPAL.*ADOBE|ADOBE.*CLOUD)`)},
	{"Netflix", "Streaming", regexp.MustCompile(`(?i)(Netflix|Stream|CB\*.*NETFLIX|PAYPAL.*NETFLIX)`)},
	{"Spotify", "Musique", regexp.MustCompile(`(?i)(Spotify|Audio|CB\*.*SPOTIFY|PAYPAL.*SPOTIFY)`)},
	{"Dropbox", "Stockage", regexp.MustCompile(`(?i)(Dropbox|Sync|CB\*.*DROPBOX|PAYPAL.*DROPBOX)`)},
	{"Zoom", "Communication", regexp.MustCompile(`(?i)(Zoom|Meeting|CB\*.*ZOOM|PAYPAL.*ZOOM)`)},
	{"Canva", "Design", regexp.MustCompile(`(?i)(Canva|Design|CB\*.*CANVA|PAYPAL.*CANVA)`)},
	{"Cloud", "Stockage Cloud", regexp.MustCompile(`(?i)(Cloud|Storage|CB\*.*CLOUD|PAYPAL.*CLOUD)`)},
	{"VPN", "CyberSécurité", regexp.MustCompile(`(?i)(VPN|Secure|Proxy|CB\*.*VPN|PAYPAL.*VPN)`)},
	{"Prime", "Services Amazon Prime", regexp.MustCompile(`(?i)(Prime|AMZN.*PRIME|CB\*.*PRIME|PAYPAL.*PRIME)`)},
	{"Game", "Jeux video", regexp.MustCompile(`(?i)(Game|Play|Gaming|CB\*.*GAME|PAYPAL.*GAME)`)},
	{"Fitness", "Fitness", regexp.MustCompile(`(?i)(Fitness|Fit|Workout|CB\*.*FITNESS|PAYPAL.*FITNESS)`)},
	{"Learn", "Education", regexp.MustCompile(`(?i)(Learn|Education|School|CB\*.*LEARN|PAYPAL.*LEARN)`)},
	{"News", "Presse", regexp.MustCompile(`(?i)(News|Press|Paper|CB\*.*NEWS|PAYPAL.*NEWS)`)},
	{"Audio", "Audio", regexp.MustCompile(`(?i)(Audio|Book|Podcast|CB\*.*AUDIO|PAYPAL.*AUDIO)`)},
	{"Photo", "Photo", regexp.MustCompile(`(?i)(Photo|Print|Image|CB\*.*PHOTO|PAYPAL.*PHOTO)`)},
	{"Delivery", "Livraison", regexp.MustCompile(`(?i)(Delivery|Deliver|Food|CB\*.*DELIVERY|PAYPAL.*DELIVERY)`)},
	{"Box", "Box", regexp.MustCompile(`(?i)(Box|Kit|Pack|CB\*.*BOX|PAYPAL.*BOX)`)},
	{"Culture", "Culture", regexp.MustCompile(`(?i)(Culture|Art|Show|CB\*.*CULTURE|PAYPAL.*CULTURE)`)},
	{"Language", "Langue", regexp.MustCompile(`(?i)(Language|Learn|Translate|CB\*.*LANGUAGE|PAYPAL.*LANGUAGE)`)},
	{"Diet", "Diet", regexp.MustCompile(`(?i)(Diet|Weight|Slim|CB\*.*DIET|PAYPAL.*DIET)`)},
	{"Wellbeing", "Bien être", regexp.MustCompile(`(?i)(Wellbeing|Mood|Relax|CB\*.*WELLBEING|PAYPAL.*WELLBEING)`)},

	{"Finance", "Services Financiers", regexp.MustCompile(`(?i)(Finance|Fintech|Banking|CB\*.*FINANCE|PAYPAL.*FINANCE)`)},
	{"Insurance", "Assurances", regexp.MustCompile(`(?i)(Insurance|Assurance|CB\*.*INSURANCE|PAYPAL.*INSURANCE)`)},
	{"Investment", "Investissements", regexp.MustCompile(`(?i)(Investment|Invest|Stocks|CB\*.*INVEST|PAYPAL.*INVEST)`)},
	{"Donation", "Dons", regexp.MustCompile(`(?i)(Donation|Donate|Charity|CB\*.*DONATION|PAYPAL.*DONATION)`)},
	{"Online", "Services en ligne", regexp.MustCompile(`(?i)(Online|Web|Internet|CB\*.*ONLINE|PAYPAL.*ONLINE)`)},
	{"Digital", "Services numériques", regexp.MustCompile(`(?i)(Digital|Software|App|CB\*.*DIGITAL|PAYPAL.*DIGITAL)`)},
	{"Payment", "Paiements", regexp.MustCompile(`(?i)(Payment|Pay|Transaction|CB\*.*PAYMENT|PAYPAL.*PAYMENT)`)},
	{"Subscription", "Abonnements", regexp.MustCompile(`(?i)(Subscription|Sub|Membership|CB\*.*SUBSCRIPTION|PAYPAL.*SUBSCRIPTION)`)},
	{"Powens", "Services Financiers", regexp.MustCompile(`(?i)(Powens|CB\*.*POWENS|PAYPAL.*POWENS)`)},
	{"Lydia", "Services Financiers", regexp.MustCompile(`(?i)(Lydia|CB\*.*LYDIA|PAYPAL.*LYDIA)`)},
	{"Nickel", "Services Bancaires", regexp.MustCompile(`(?i)(Nickel|CB\*.*NICKEL|PAYPAL.*NICKEL)`)},
	{"Revolut", "Services Bancaires", regexp.MustCompile(`(?i)(Revolut|CB\*.*REVOLUT|PAYPAL.*REVOLUT)`)},
	{"Boursorama", "Services Bancaires", regexp.MustCompile(`(?i)(Boursorama|CB\*.*BOURSORAMA|PAYPAL.*BOURSORAMA)`)},
	{"Fortuneo", "Services Bancaires", regexp.MustCompile(`(?i)(Fortuneo|CB\*.*FORTUNEO|PAYPAL.*FORTUNEO)`)},
	{"Hello bank!", "Services Bancaires", regexp.MustCompile(`(?i)(Hello bank!|CB\*.*HELLOBANK|PAYPAL.*HELLOBANK)`)},
	{"Orange Bank", "Services Bancaires", regexp.MustCompile(`(?i)(Orange Bank|CB\*.*ORANGEBANK|PAYPAL.*ORANGEBANK)`)},
	{"N26", "Services Bancaires", regexp.MustCompile(`(?i)(N26|CB\*.*N26|PAYPAL.*N26)`)},
	{"Société Générale", "Services Bancaires", regexp.MustCompile(`(?i)(Société Générale|CB\*.*SOCIETEGENERALE|PAYPAL.*SOCIETEGENERALE)`)},
	{"BNP Paribas", "Services Bancaires", regexp.MustCompile(`(?i)(BNP Paribas|CB\*.*BNP|PAYPAL.*BNP)`)},
	{"Crédit Agricole", "Services Bancaires", regexp.MustCompile(`(?i)(Crédit Agricole|CB\*.*CREDITAGRICOLE|PAYPAL.*CREDITAGRICOLE)`)},
	{"La Banque Postale", "Services Bancaires", regexp.MustCompile(`(?i)(La Banque Postale|CB\*.*LABANQUEPOSTALE|PAYPAL.*LABANQUEPOSTALE)`)},
	{"CIC", "Services Bancaires", regexp.MustCompile(`(?i)(CIC|CB\*.*CIC|PAYPAL.*CIC)`)},
	{"bitstack", "Services Financiers", regexp.MustCompile(`(?i)(bitstack|CB\*.*bitstack|PAYPAL.*bitstack)`)},
}
